/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as BazaarRouteImport } from './routes/bazaar'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PreservationRouteImport } from './routes/preservation'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as TrailsRouteImport } from './routes/trails'
import { Route as CraftsSlugRouteImport } from './routes/crafts.$slug'
import { Route as CulinarySlugRouteImport } from './routes/culinary.$slug'
import { Route as FestivalsSlugRouteImport } from './routes/festivals.$slug'
import { Route as HeritageSlugRouteImport } from './routes/heritage.$slug'
import { Route as PerformingArtsSlugRouteImport } from './routes/performing-arts.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const BazaarRoute = BazaarRouteImport.update({
  id: '/bazaar',
  path: '/bazaar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PreservationRoute = PreservationRouteImport.update({
  id: '/preservation',
  path: '/preservation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const TrailsRoute = TrailsRouteImport.update({
  id: '/trails',
  path: '/trails',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftsSlugRoute = CraftsSlugRouteImport.update({
  id: '/crafts/$slug',
  path: '/crafts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CulinarySlugRoute = CulinarySlugRouteImport.update({
  id: '/culinary/$slug',
  path: '/culinary/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsSlugRoute = FestivalsSlugRouteImport.update({
  id: '/festivals/$slug',
  path: '/festivals/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageSlugRoute = HeritageSlugRouteImport.update({
  id: '/heritage/$slug',
  path: '/heritage/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformingArtsSlugRoute = PerformingArtsSlugRouteImport.update({
  id: '/performing-arts/$slug',
  path: '/performing-arts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/assistant': typeof AssistantRoute
  '/bazaar': typeof BazaarRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/preservation': typeof PreservationRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/reels': typeof ReelsRoute
  '/trails': typeof TrailsRoute
  '/crafts/$slug': typeof CraftsSlugRoute
  '/culinary/$slug': typeof CulinarySlugRoute
  '/festivals/$slug': typeof FestivalsSlugRoute
  '/heritage/$slug': typeof HeritageSlugRoute
  '/performing-arts/$slug': typeof PerformingArtsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/assistant': typeof AssistantRoute
  '/bazaar': typeof BazaarRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/preservation': typeof PreservationRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/reels': typeof ReelsRoute
  '/trails': typeof TrailsRoute
  '/crafts/$slug': typeof CraftsSlugRoute
  '/culinary/$slug': typeof CulinarySlugRoute
  '/festivals/$slug': typeof FestivalsSlugRoute
  '/heritage/$slug': typeof HeritageSlugRoute
  '/performing-arts/$slug': typeof PerformingArtsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/assistant': typeof AssistantRoute
  '/bazaar': typeof BazaarRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/preservation': typeof PreservationRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/reels': typeof ReelsRoute
  '/trails': typeof TrailsRoute
  '/crafts/$slug': typeof CraftsSlugRoute
  '/culinary/$slug': typeof CulinarySlugRoute
  '/festivals/$slug': typeof FestivalsSlugRoute
  '/heritage/$slug': typeof HeritageSlugRoute
  '/performing-arts/$slug': typeof PerformingArtsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/archive'
    | '/assistant'
    | '/bazaar'
    | '/explore'
    | '/login'
    | '/preservation'
    | '/profile'
    | '/quiz'
    | '/reels'
    | '/trails'
    | '/crafts/$slug'
    | '/culinary/$slug'
    | '/festivals/$slug'
    | '/heritage/$slug'
    | '/performing-arts/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/archive'
    | '/assistant'
    | '/bazaar'
    | '/explore'
    | '/login'
    | '/preservation'
    | '/profile'
    | '/quiz'
    | '/reels'
    | '/trails'
    | '/crafts/$slug'
    | '/culinary/$slug'
    | '/festivals/$slug'
    | '/heritage/$slug'
    | '/performing-arts/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/archive'
    | '/assistant'
    | '/bazaar'
    | '/explore'
    | '/login'
    | '/preservation'
    | '/profile'
    | '/quiz'
    | '/reels'
    | '/trails'
    | '/crafts/$slug'
    | '/culinary/$slug'
    | '/festivals/$slug'
    | '/heritage/$slug'
    | '/performing-arts/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArchiveRoute: typeof ArchiveRoute
  AssistantRoute: typeof AssistantRoute
  BazaarRoute: typeof BazaarRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  PreservationRoute: typeof PreservationRoute
  ProfileRoute: typeof ProfileRoute
  QuizRoute: typeof QuizRoute
  ReelsRoute: typeof ReelsRoute
  TrailsRoute: typeof TrailsRoute
  CraftsSlugRoute: typeof CraftsSlugRoute
  CulinarySlugRoute: typeof CulinarySlugRoute
  FestivalsSlugRoute: typeof FestivalsSlugRoute
  HeritageSlugRoute: typeof HeritageSlugRoute
  PerformingArtsSlugRoute: typeof PerformingArtsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bazaar': {
      id: '/bazaar'
      path: '/bazaar'
      fullPath: '/bazaar'
      preLoaderRoute: typeof BazaarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preservation': {
      id: '/preservation'
      path: '/preservation'
      fullPath: '/preservation'
      preLoaderRoute: typeof PreservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trails': {
      id: '/trails'
      path: '/trails'
      fullPath: '/trails'
      preLoaderRoute: typeof TrailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crafts/$slug': {
      id: '/crafts/$slug'
      path: '/crafts/$slug'
      fullPath: '/crafts/$slug'
      preLoaderRoute: typeof CraftsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culinary/$slug': {
      id: '/culinary/$slug'
      path: '/culinary/$slug'
      fullPath: '/culinary/$slug'
      preLoaderRoute: typeof CulinarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals/$slug': {
      id: '/festivals/$slug'
      path: '/festivals/$slug'
      fullPath: '/festivals/$slug'
      preLoaderRoute: typeof FestivalsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage/$slug': {
      id: '/heritage/$slug'
      path: '/heritage/$slug'
      fullPath: '/heritage/$slug'
      preLoaderRoute: typeof HeritageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performing-arts/$slug': {
      id: '/performing-arts/$slug'
      path: '/performing-arts/$slug'
      fullPath: '/performing-arts/$slug'
      preLoaderRoute: typeof PerformingArtsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArchiveRoute: ArchiveRoute,
  AssistantRoute: AssistantRoute,
  BazaarRoute: BazaarRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  PreservationRoute: PreservationRoute,
  ProfileRoute: ProfileRoute,
  QuizRoute: QuizRoute,
  ReelsRoute: ReelsRoute,
  TrailsRoute: TrailsRoute,
  CraftsSlugRoute: CraftsSlugRoute,
  CulinarySlugRoute: CulinarySlugRoute,
  FestivalsSlugRoute: FestivalsSlugRoute,
  HeritageSlugRoute: HeritageSlugRoute,
  PerformingArtsSlugRoute: PerformingArtsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
